logging:
  level:
    root: warn
    com.ghsong.myboard: debug

server:
  port: 1647

spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/board?characterEncoding=UTF-8&serverTimezone=UTC
    username: board
    password: 1646
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      format-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    generate-ddl: true